project:
  type: website 
  output-dir: docs

website:
  title: "Catherine's Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "CV"
        href: Punnoose_Catherine_UXD_Resume2024.pdf
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

